[book]
authors = ["Tim Dams"]
language = "nl"
multilingual = false
src = "."
title = "Zie Scherp Scherper"
description="Leer programmeren in csharp."

[output.html.fold]
enable = true

[output.html]
no-section-label = true
